services:
  - type: web
    name: samad-nursing-home-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: NPM_CONFIG_PRODUCTION
        value: false
    healthCheckPath: /health
    autoDeploy: true 